//------------------------------------------------------------------------------
// <auto-generated>
//    このコードはテンプレートから生成されました。
//
//    このファイルを手動で変更すると、アプリケーションで予期しない動作が発生する可能性があります。
//    このファイルに対する手動の変更は、コードが再生成されると上書きされます。
// </auto-generated>
//------------------------------------------------------------------------------

namespace WYsystem.Models
{
    using System;
    using System.Collections.Generic;
    using System.ComponentModel;

    public partial class w_announcement
    {
        public int id { get; set; }


        [DisplayName("お知らせID")]
        public string number { get; set; }


        [DisplayName("タイトル")]
        public string title { get; set; }


        [DisplayName("作成日")]
        public Nullable<System.DateTime> createtime { get; set; }


        [DisplayName("内容")]
        public string contents { get; set; }
        public Nullable<int> uid { get; set; }


        [DisplayName("管理者名")]
        public string nickname { get; set; }
    }
}
