//------------------------------------------------------------------------------
// <auto-generated>
//    このコードはテンプレートから生成されました。
//
//    このファイルを手動で変更すると、アプリケーションで予期しない動作が発生する可能性があります。
//    このファイルに対する手動の変更は、コードが再生成されると上書きされます。
// </auto-generated>
//------------------------------------------------------------------------------

namespace WYsystem.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class w_room_info
    {
        public int id { get; set; }
        public string name { get; set; }
        public string phone { get; set; }
        public string link_name { get; set; }
        public Nullable<int> stop_car_area { get; set; }
        public Nullable<System.DateTime> construct_date { get; set; }
        public Nullable<int> road_area { get; set; }
        public Nullable<int> room_area { get; set; }
        public Nullable<int> lh_area { get; set; }
        public Nullable<int> room_number { get; set; }
        public string address { get; set; }
        public string remark { get; set; }
    }
}
